import profilePic from "../../assets/images/mentor-pic.png";
const Data = [
  {
    id: 1,
    name: "Don Normal",
    profilePic: { profilePic },
    tag: "topRated",
    language: "English",
    designation: "Designer",
    organization: "Apple.inc",
    experience: "5 Years",
    slotTime: "12 Dec, 8:00 PM",
  },
  {
    id: 2,
    name: "Don Normal",
    profilePic: { profilePic },
    // "tag":"Exclusive",
    language: "English",
    designation: "Designer",
    organization: "Apple.inc",
    experience: "5 Years",
    slotTime: "12 Dec, 8:00 PM",
    sessionsConducted: 6,
  },
  {
    id: 3,
    name: "Don Normal",
    profilePic: { profilePic },
    // "tag":"Exclusive",
    language: "English",
    designation: "Designer",
    organization: "Apple.inc",
    experience: "5 Years",
    slotTime: "12 Dec, 8:00 PM",
    sessionsConducted: 6,
  },
  {
    id: 4,
    name: "Don Normal",
    profilePic: { profilePic },
    // "tag":"Exclusive",
    language: "English",
    designation: "Designer",
    organization: "Apple.inc",
    experience: "5 Years",
    slotTime: "12 Dec, 8:00 PM",
  },
];
export default Data;
